# Generated by Django 6.1.1 on 2026-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0003_coursemodule_lesson_quiz_question_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(default='PENDING_ADMIN_APPROVAL', max_length=40),
        ),
    ]
